apiVersion: v1
data:
  metrics.conf: |-
    baidu,https://www.baidu.com/
    test,https://www.baidu.com/qwe
kind: ConfigMap
metadata:
  name: metrics
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
  namespace: default
spec:
  minReadySeconds: 20
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: metrics
  replicas: 1
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
      - name: metrics
        image: registry.cn-shanghai.aliyuncs.com/baiyuani/metrics:0.0.6
        imagePullPolicy: IfNotPresent
        resources:
          requests: 
            cpu: 100m
            memory: 128Mi
          limits: 
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /metrics
            port: 5000
            scheme: HTTP
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          httpGet:
            path: /metrics
            port: 5000
            scheme: HTTP
          timeoutSeconds: 30
#        startupProbe:
#          failureThreshold: 3
#          initialDelaySeconds: 30
#          periodSeconds: 30
#          successThreshold: 1
#          httpGet:
#            path: /metrics
#            port: 5000
#            scheme: HTTP
#          timeoutSeconds: 30
        volumeMounts:
        - name: metrics
          mountPath: /metrics/src/configuration
        ports:
        - containerPort: 5000
          protocol: TCP
      volumes:
        - configMap:
            name: metrics
          name: metrics
#      imagePullSecrets:
#        - name: docker-registry
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: metrics
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: metrics
  sessionAffinity: None
  type: ClusterIP
